export const WS_URL_ORDERS = 'wss://norma.nomoreparties.space/orders';
export const WS_URL_ORDERS_ALL = 'wss://norma.nomoreparties.space/orders/all';

export const WS_CONNECTION_START_ORDERS: 'WS_CONNECTION_START_ORDERS' = 'WS_CONNECTION_START_ORDERS';
export const WS_CONNECTION_SUCCESS_ORDERS: 'WS_CONNECTION_SUCCESS_ORDERS' = 'WS_CONNECTION_SUCCESS_ORDERS';
export const WS_CONNECTION_ERROR_ORDERS: 'WS_CONNECTION_ERROR_ORDERS' = 'WS_CONNECTION_ERROR_ORDERS';
export const WS_CONNECTION_CLOSED_ORDERS: 'WS_CONNECTION_CLOSED_ORDERS' = 'WS_CONNECTION_CLOSED_ORDERS';
export const WS_CONNECTION_CLOSE_ORDERS: 'WS_CONNECTION_CLOSE_ORDERS' = 'WS_CONNECTION_CLOSE_ORDERS';
export const WS_GET_MESSAGE_ORDERS: 'WS_GET_MESSAGE_ORDERS' = 'WS_GET_MESSAGE_ORDERS';
export const WS_SEND_MESSAGE_ORDERS: 'WS_SEND_MESSAGE_ORDERS' = 'WS_SEND_MESSAGE_ORDERS';

export const WS_CONNECTION_START_ORDERS_ALL: 'WS_CONNECTION_START_ORDERS_ALL' = 'WS_CONNECTION_START_ORDERS_ALL';
export const WS_CONNECTION_SUCCESS_ORDERS_ALL: 'WS_CONNECTION_SUCCESS_ORDERS_ALL' = 'WS_CONNECTION_SUCCESS_ORDERS_ALL';
export const WS_CONNECTION_ERROR_ORDERS_ALL: 'WS_CONNECTION_ERROR_ORDERS_ALL' = 'WS_CONNECTION_ERROR_ORDERS_ALL';
export const WS_CONNECTION_CLOSED_ORDERS_ALL: 'WS_CONNECTION_CLOSED_ORDERS_ALL' = 'WS_CONNECTION_CLOSED_ORDERS_ALL';
export const WS_CONNECTION_CLOSE_ORDERS_ALL: 'WS_CONNECTION_CLOSE_ORDERS_ALL' = 'WS_CONNECTION_CLOSE_ORDERS_ALL';
export const WS_GET_MESSAGE_ORDERS_ALL: 'WS_GET_MESSAGE_ORDERS_ALL' = 'WS_GET_MESSAGE_ORDERS_ALL';
export const WS_SEND_MESSAGE_ORDERS_ALL: 'WS_SEND_MESSAGE_ORDERS_ALL' = 'WS_SEND_MESSAGE_ORDERS_ALL';
